language: java
jdk: oraclejdk8
sudo: required
before_install:
- cat /home/travis/build/HanaBenami/RT/src/main/resources/VAADIN/themes/mytheme/styles.css
- cat /home/travis/build/HanaBenami/RT/src/main/resources/VAADIN.themes/mytheme/styles.scss
- cat /home/travis/build/HanaBenami/RT/src/main/resources/VAADIN/themes/mytheme/styles.scss
- chmod +x mvnw