spring:
  profiles: prod

server:
  port: 8084

sqlserver:
  url: jdbc:sqlserver://localhost:1433;databaseName=RT;user=RT_user;password=RTrt123!;trustServerCertificate=true
log:
  path: /home/hana/RT/logs/
  sql:
    level: info
  hash:
    level: info

settings:
  multiLanguage: false
  testEnvironment: false
  bigScreen:
    rowHeight: 55
    rowsPerColumn: 20
    interval: 60000
    showCallsWithoutArea: true
  workOrderWidth: 1400
  hashSync:
    executeScheduleSync: false
    scheduleSyncFixedDelayMiliseconds: 3600000
    scheduleSyncInitialDelayMiliseconds: 60000
    syncNewCustomers: true
    syncOnlyDiff: true
    syncOnlyListedCustomers: true
    hashavshevetCustomerIdsToSync: 2716, 2326, 20637
