spring:
  profiles: dev

server:
  port: 8083

sqlserver:
  url: jdbc:sqlserver://localhost;databaseName=RT_prod;user=SA;password=Hana1989

log:
  path: c:\\rt\\logs\\dev

vaadin:
  servlet:
    productionMode: false

settings:
  testEnvironment: false
  multiLanguage: true
  hashSync:
    executeScheduleSync: false
    scheduleSyncFixedDelayMiliseconds: 3600000
    scheduleSyncInitialDelayMiliseconds: 60000
    syncNewCustomers: true
    syncOnlyDiff: true
    syncOnlyListedCustomers: true
    hashavshevetCustomerIdsToSync: 2716, 2326, 20637
