spring:
  profiles: prod

server:
  port: 8084

sqlserver:
  url: jdbc:sqlserver://localhost:1433;databaseName=RT;user=RT_user;password=RTrt123!;trustServerCertificate=true
log:
  path: /home/hana/RT/logs/

settings:
  multiLanguage: false
  bigScreen:
    rowHeight: 55
    rowsPerColumn: 20
    interval: 60000
  workOrderWidth: 1400
  hashSync:
    executeSync: true
    createNewCustomers: false
    syncOnlyDiff: true
    syncOnlyListedCustomers: true
    hashavshevetCustomerIds: 2716, 2326, 20637
    fixedDelayMiliseconds: 3600000
    initialDelayMiliseconds: 60000