spring:
  profiles: dev

server:
  port: 8083

sqlserver:
  url: jdbc:sqlserver://zeev-asus:1433;databaseName=RT;integratedSecurity=true
log:
  path: c:\\rt\\logs\\dev

vaadin:
  servlet:
    productionMode: false

settings:
  multiLanguage: true