spring:
  profiles: prod

server:
  port: 8084

sqlserver:
  url: jdbc:sqlserver://zeev-asus:1433;databaseName=RT;integratedSecurity=true
log:
  path: c:\\rt\\logs\\prod

settings:
  multiLanguage: false
  bigScreen:
    rowHeight: 65
    rowsPerColumn: 14
    interval: 60000
  workOrderWidth: 1400
