spring:
  profiles:
    active: dev

vaadin:
  servlet:
    productionMode: true

settings:
  multiLanguage: false
  bigScreen:
    rowHeight: 70
    rowsPerColumn: 10
    interval: 60000
  workOrderWidth: 1400
