spring:
  profiles: demo
  datasource:
    url: jdbc:h2:~/demo;MODE=MSSQLServer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8088

log:
  path: c:\\rt\\logs\\demo

settings:
  multiLanguage: true
  workOrderWidth: 1400
  bigScreen:
    rowHeight: 70
    rowsPerColumn: 10
    interval: 60000
