spring:
  profiles: dev

server:
  port: 8083

sqlserver:
  url: jdbc:sqlserver://localhost;databaseName=RT_PROD;user=SA;password=Hana1989;


log:
  path: c:\\rt\\logs\\dev

vaadin:
  servlet:
    productionMode: false

settings:
  multiLanguage: true